version: '2'
services:
    mysql:
        build: .
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: upskilling
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"
